version: '3.7'

services:
  database:
    container_name: prisma-database
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - prisma-volume:/data/postgres

volumes:
  prisma-volume:
    driver: local
